name: LightBlockCrafting
version: '${version}'
main: net.lightblockcrafting.LightBlockCraftingPlugin
api-version: '1.19'
author: nlckl
description: Craftable, visible light blocks in 15 brightness levels - vanilla- and survival-friendly.

commands:
  lightblock:
    description: Admin command for light blocks.
    usage: /lightblock give <level> [player]
    permission: lightblockcrafting.admin

permissions:
  lightblockcrafting.admin:
    description: Allows giving light blocks via command.
    default: op
